laravel/routes/web.php
<?php

// Route::get('/', )->name('home');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('contact/', 'HomeController@contact')->name('contact');
Route::get('about/', 'HomeController@about')->name('about');
Route::get('job-register/', 'HomeController@job_register')->name('job-register');
Route::get('/search-for/{id}/{name?}', 'HomeController@search')->name('home-search');
Route::post('send-otp/', 'EnquiryController@otp')->name('otp');
Route::post('check-otp/', 'EnquiryController@checkOtp')->name('check-otp');

Route::get('search/{category?}/{from?}/{to?}', 'WorkerController@search')->name('search');
Route::resource('enquiry', 'EnquiryController');
Route::resource('contact', 'ContactController');
Route::resource('payment', 'PaymentController');
Route::post('/placeorder','PaymentController@getPay')->name('placeorder');	
Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');
Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::resource('qualification', 'QualificationController');
Route::resource('blood-group', 'BloodGroupController');
Route::resource('language', 'LanguageController');
Route::resource('category', 'CategoryController');

Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('worker', 'UserDetailController');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function() {
	Route::get('/', function(){
		return view('admin.dashboard');
	})->name('home');

	Route::get('images', function (){
		
		return view('admin.upload');
	})->name('g-images');
	Route::resource('qualification', 'QualificationController');
	Route::resource('language', 'LanguageController');
	Route::resource('blood-group', 'BloodGroupController');
	Route::resource('category', 'CategoryController');
	Route::post('images', 'UserDetailController@images')->name('images');
	Route::resource('sub-category', 'SubCategoryController');
	Route::resource('enquiry', 'EnquiryController');	
	Route::resource('contact', 'ContactController');
	Route::resource('payment', 'PaymentController');
	Route::resource('employee', 'WorkerController');

});

laravel/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function detail(){
        return $this->hasOne(\App\Models\UserDetail::class, 'ud_user');
    }
}

laravel/resources/views/user/layouts/footer.blade.php
@if (Route::currentRouteName() != "payment.create")	
<a href = "{{ route('payment.create') }}" id="myBtn" title="Pay your Bills here">Pay via PayUMoney</a>
@endif

<!-- footer start -->
<footer>
	<!-- footer-top-area start -->
	<div class="footer-top-area">
		<div class="container">
			<div class="row">
				<!-- footer-widget start -->
				<div class="col-lg-3 col-md-3 col-sm-4">
					<div class="footer-widget">
						<img src="{{ asset('images/logo.png') }}" alt="" width="100%" />
						<p></p>
						<div class="widget-icon">
							<a href="https://www.facebook.com/Durable-Facility-Management-Services-Pvt-Ltd-1503700849727172/"><i class="fa fa-facebook fb"></i></a>
							<a href="https://twitter.com/BarideSachin/"><i class="fa fa-twitter tw"></i></a>
							<a href="https://www.linkedin.com/in/sachin-baride-10392715b/"><i class="fa fa-linkedin ln"></i></a>
							<a href="https://plus.google.com/u/4/104692814929014250380/"><i class="fa fa-google-plus gp"></i></a>
							<a href="https://www.instagram.com/dfmspl/"><i class="fa fa-instagram instagram"></i></a>
						</div>
					</div>
				</div>
				<!-- footer-widget end -->
				<!-- footer-widget start -->
				<div class="col-lg-3 col-md-3 hidden-sm">
					<div class="footer-widget">
						<h3>Our services</h3>
						<p>We are India's largest online aggregator of maid bureaus. Whether you are looking for a maid or a nanny or a patient caretaker in All India. You will find the best quality and experienced staff here.</p>
					</div>
				</div>
				<!-- footer-widget end -->
				<!-- footer-widget start -->
				<div class="col-lg-3 col-md-3 col-sm-4">
					<div class="footer-widget">
						<h3>Useful Links</h3>
						<ul class="footer-menu">
							<li><a href="{{ route('home') }}">Home</a></li>
							<li><a href="{{ route('about') }}">About us</a></li>
							<li><a href="{{ route('contact.create') }}"> Contact us</a></li>
						</ul>
					</div>
				</div>
				<!-- footer-widget end -->
				<!-- footer-widget start -->
				<div class="col-lg-3 col-md-3 col-sm-4">
					<div class="footer-widget">
						<h3>CONTACT US</h3>
						<ul class="footer-contact">
							<li>
								<i class="fa fa-map-marker"> </i>
								Addresss: Pune, Maharashtra.
							</li>
							<li>
								<i class="fa fa-envelope"> </i>	
								Email: dfmspl1@gmail.com, support@dfmspl.com
							</li>
							<li>
								<i class="fa fa-phone"> </i>
								Phone: +91 77210 44526
							</li>
						</ul>
					</div>
				</div>
				<!-- footer-widget end -->
			</div>
		</div>
	</div>
	<!-- footer-top-area end -->
	<!-- footer-bottom-area start -->
	<div class="footer-bottom-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-8 col-sm-6">
					<div class="copyright">
						<p>&copy; 2018 Facility . All Rights Reserved | Design by <a href="http://sungare.com/">Sungare</a>. All Rights Reserved</p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-6">
					<div class="payment-img">
						<img src="{{ asset('images/pay.png') }}" alt="Support All Payment Methods" width="100%" />
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- footer-bottom-area end -->
</footer>
<!-- footer end -->
<div><script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script></div>

<script src="{{ asset('admin-assets/js/crud.min.js') }}"></script>

<script src="{{ asset('js/responsiveslides.min.js') }}"></script>
<!-- gallery-pop-up-script -->
<script src="{{ asset('js/jquery.chocolat.min.js') }}"></script>
<!-- //gallery-pop-up-script -->

<script defer src="{{ asset('js/jquery.flexslider.min.js') }}"></script>

<script src="{{ asset('js/SmoothScroll.min.js') }}"></script>

<!--Start-slider-script-->
<script type="text/javascript">
	// You can also use "$(window).load(function() {"
	$(function () {
	// Slideshow 4
	$("#slider4").responsiveSlides({
		auto: true,
		pager:true,
		nav:false,
		speed: 400,
		namespace: "callbacks",
		before: function () {
			$('.events').append("<li>before event fired.</li>");
		},
		after: function () {
			$('.events').append("<li>after event fired.</li>");
		}
	});

});
	$(window).load(function(){
		$('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
				$('body').removeClass('loading');
			}
		});
	});
</script>


<script>
	$(window).on('load',function(){
		$('#loader').addClass('hidden');
	});
	window.onscroll = function() {scrollFunction()};

	function scrollFunction() {
		if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
			document.getElementById("myBtn").style.display = "block";
		} else {
			document.getElementById("myBtn").style.display = "none";
		}
	}
</script>
<script type="text/javascript">
	function googleTranslateElementInit() {
		new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
	}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
@stack('footer')
</body>	
</html>

laravel/resources/views/user/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Facility Management @yield('title')</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<link rel="shortcut icon" href="{{ asset('images/fav.png') }}">
	<meta name="keywords" content="" />
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<style type="text/css">
	#loader{
		position: fixed;
		background-color: white;
		width: 100%;
		height: 1000px;
		z-index: 1111;
		text-align: center;
		padding: 20%;
	}
	#google_translate_element{
		position: absolute;
		right: 0;
		top: 0;
	}</style>

	@if (config('app.env') == 'local')
	<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all" />	
	<link rel="stylesheet" href="{{ asset('css/chocolat.css') }}" type="text/css">	
	<link rel="stylesheet" href="{{ asset('css/style.css') }}" type="text/css" media="all" />
	<link rel="stylesheet" href="{{ asset('css/flexslider.css') }}" type="text/css" media="screen" />
	<link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet"> 
	
	@else
	<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" media="all" />	
	<link rel="stylesheet" href="{{ asset('css/chocolat.min.css') }}" type="text/css">	
	<link rel="stylesheet" href="{{ asset('css/style.min.css') }}" type="text/css" media="all" />
	<link rel="stylesheet" href="{{ asset('css/flexslider.min.css') }}" type="text/css" media="screen" />
	<link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet"> 

	@endif
	
	<script type='text/javascript' src="{{ asset('js/jquery-1.11.1.min.js') }}"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}"></script>

	@stack('header')
</head>
<body @yield('body')>
	<div id = "loader">
		<img src="{{ asset('images/loader.gif') }}" width = "100">
	</div>
	<!-- banner -->
	<div class="banner">
		<div class="agile_dot_info">
			<div class="w3-header-bottom">
				<div class="container">
					<div class="w3layouts-logo">
						<a href="{{ route('home') }}"><img src="{{ asset('images/logo.png') }}"> </a>
					</div>


					<div class="top-nav">
						<nav class="navbar navbar-default">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
							</div>
							<h1>Durable Facility Management Service Pvt. Ltd.</h1>
							<p> Hard work & faith is our identity</p>							
							<div class="clearfix"> </div>
						</nav>	
					</div>					
					<div class="clearfix"> </div>
					<div id="google_translate_element"></div>
				</div>
			</div>
			<div class="sub-header">
				<div class="collapse navbar-collapse  no-padding" id="bs-example-navbar-collapse-1">
					
					<ul class="nav navbar-nav">
						@forelse (App\Models\Category::get() as $cat)
						@php
						$r = route('home-search', ['name' => str_replace(' ', '-',strtolower($cat->cat_title)), 'id' => $cat->cat_id]);
						if($cat->cat_type){
							$r = route('search',['category' => $cat->subCategory->first()->scat_id]);
						}
						@endphp
						<li><a href="{{ $r }}">{{ $cat->cat_title }}</a></li>
						@empty

						@endforelse
						<li><a href="{{ route('about') }}">About Us</a></li>
						<li><a href="{{ route('payment.create') }}">Payment</a></li>
						<li><a href="{{ route('job-register') }}">Register for Job</a></li>
					</ul>	
					<div class="clearfix"> </div>
				</div>	
			</div>

laravel/resources/views/user/layouts/master.blade.php
@include('user.layouts.header')
@yield('content')
@include('user.layouts.footer')