laravel/routes/web.php
<?php

// Route::get('/', )->name('home');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('contact/', 'HomeController@contact')->name('contact');
Route::get('about/', 'HomeController@about')->name('about');
Route::get('job-register/', 'HomeController@job_register')->name('job-register');
Route::get('/search-for/{id}/{name?}', 'HomeController@search')->name('home-search');
Route::post('send-otp/', 'EnquiryController@otp')->name('otp');
Route::post('check-otp/', 'EnquiryController@checkOtp')->name('check-otp');

Route::get('search/{category?}/{from?}/{to?}', 'WorkerController@search')->name('search');
Route::resource('enquiry', 'EnquiryController');
Route::resource('contact', 'ContactController');
Route::resource('payment', 'PaymentController');
Route::post('/placeorder','PaymentController@getPay')->name('placeorder');	
Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');
Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::resource('qualification', 'QualificationController');
Route::resource('blood-group', 'BloodGroupController');
Route::resource('language', 'LanguageController');
Route::resource('category', 'CategoryController');

Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('worker', 'UserDetailController');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function() {
	Route::get('/', function(){
		return view('admin.dashboard');
	})->name('home');

	Route::get('images', function (){
		
		return view('admin.upload');
	})->name('g-images');
	Route::resource('qualification', 'QualificationController');
	Route::resource('language', 'LanguageController');
	Route::resource('blood-group', 'BloodGroupController');
	Route::resource('category', 'CategoryController');
	Route::post('images', 'UserDetailController@images')->name('images');
	Route::resource('sub-category', 'SubCategoryController');
	Route::resource('enquiry', 'EnquiryController');	
	Route::resource('contact', 'ContactController');
	Route::resource('payment', 'PaymentController');
	Route::resource('employee', 'WorkerController');

});

laravel/resources/views/admin/layouts/footer.blade.php
        <!-- footer content -->
        <footer>
          <div class="pull-right">
            {{ config('app.name') }}
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
</div>
</div>

<!-- jQuery -->
<script src="{{ asset('admin-assets/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('admin-assets/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin-assets/fastclick/lib/fastclick.js') }}"></script>
<!-- NProgress -->
<script src="{{ asset('admin-assets/nprogress/nprogress.js') }}"></script>
<script src="{{ asset('admin-assets/js/custom.js') }}"></script>
<script src="{{ asset('admin-assets/js/crud.js') }}"></script>
@stack('footer')
</body>
</html>

laravel/resources/views/admin/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Durable Facility Management (Admin) | @yield('title')</title>
  <link rel="shortcut icon" type="image/x-icon" href="{{ asset('img/icon-img/favicon.ico') }}">

  <!-- Bootstrap -->
  <link href="{{ asset('admin-assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{{ asset('admin-assets/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{{ asset('admin-assets/nprogress/nprogress.css') }}" rel="stylesheet">
  <!-- bootstrap-daterangepicker -->
  <link href="{{ asset('admin-assets/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="{{ asset('admin-assets/css/custom.css') }}" rel="stylesheet">

  @stack('header')
</head>

<body class="nav-md">

  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{{ route('admin.home') }}" class="site_title"> <span>{{ config('app.name') }}</span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="{{ asset('admin-assets/images/img.jpg') }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2>{{ Auth::user()->name }}</h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              {{-- <h3>General</h3> --}}
              <ul class="nav side-menu">
                <li><a href="{{ route('admin.enquiry.index') }}"><i class="fa fa-home"></i> Enquiries</a>                  
                </li>               
                <li><a href="{{ route('admin.contact.index') }}"><i class="fa fa-home"></i> Contact Enquiries</a></li>
                <li><a href="{{ route('admin.payment.index') }}"><i class="fa fa-home"></i>View Payments</a></li>
                <li><a href="{{ route('admin.employee.index') }}"><i class="fa fa-home"></i>Employees</a></li>
                {{--<li><a><i class="fa fa-home"></i> Categories <span class="fa fa-chevron-down"></span></a>--}}
                  {{--<ul class="nav child_menu">--}}
                    {{--<li><a href="{{ route('admin.category.index') }}">Category List</a></li>--}}
                    {{--<li><a href="{{ route('admin.category.create') }}">Add Category</a></li>--}}
                  {{--</ul>--}}
                {{--</li>--}}
                {{--<li><a><i class="fa fa-home"></i> Sub Categories <span class="fa fa-chevron-down"></span></a>--}}
                  {{--<ul class="nav child_menu">--}}
                    {{--<li><a href="{{ route('admin.sub-category.index') }}">Sub Category List</a></li>--}}
                    {{--<li><a href="{{ route('admin.sub-category.create') }}">Add Sub Category</a></li>--}}
                  {{--</ul>--}}
                {{--</li>--}}
              </ul>
            </div>
            

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small hidden">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Log Out <i class="fa fa-sign-out"></i> 
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  {{ csrf_field() }}
                </form>                
              </li>                      
            </ul>
          </nav>
        </div>
      </div>
        <!-- /top navigation -->

laravel/resources/views/admin/layouts/master.blade.php
@include('admin.layouts.header')
@yield('content')
@include('admin.layouts.footer')