laravel/routes/web.php
<?php

// Route::get('/', )->name('home');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('contact/', 'HomeController@contact')->name('contact');
Route::get('about/', 'HomeController@about')->name('about');
Route::get('job-register/', 'HomeController@job_register')->name('job-register');
Route::get('/search-for/{id}/{name?}', 'HomeController@search')->name('home-search');
Route::post('send-otp/', 'EnquiryController@otp')->name('otp');
Route::post('check-otp/', 'EnquiryController@checkOtp')->name('check-otp');

Route::get('search/{category?}/{from?}/{to?}', 'WorkerController@search')->name('search');
Route::resource('enquiry', 'EnquiryController');
Route::resource('contact', 'ContactController');
Route::resource('payment', 'PaymentController');
Route::post('/placeorder','PaymentController@getPay')->name('placeorder');	
Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');
Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::resource('qualification', 'QualificationController');
Route::resource('blood-group', 'BloodGroupController');
Route::resource('language', 'LanguageController');
Route::resource('category', 'CategoryController');

Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('worker', 'UserDetailController');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function() {
	Route::get('/', function(){
		return view('admin.dashboard');
	})->name('home');

	Route::get('images', function (){
		
		return view('admin.upload');
	})->name('g-images');
	Route::resource('qualification', 'QualificationController');
	Route::resource('language', 'LanguageController');
	Route::resource('blood-group', 'BloodGroupController');
	Route::resource('category', 'CategoryController');
	Route::post('images', 'UserDetailController@images')->name('images');
	Route::resource('sub-category', 'SubCategoryController');
	Route::resource('enquiry', 'EnquiryController');	
	Route::resource('contact', 'ContactController');
	Route::resource('payment', 'PaymentController');
	Route::resource('employee', 'WorkerController');

});

laravel/resources/views/admin/create_worker.blade.php
@extends('admin.layouts.master')
@php
$ID = 'worker';
@endphp
@push('header')
<script>
	ID = '{{ $ID }}';
</script>
<style type="text/css">
img {
	object-fit: contain;
}
</style>
@section('title')
Create {{ ucwords($ID) }}
@endsection
<link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" />
@endpush
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Register {{ ucwords($ID) }}</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/form-data">
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Name
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="text" class="form-control col-md-7 col-xs-12" name = "name">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Mobile
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="number" class="form-control col-md-7 col-xs-12" name = "mobile">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Alternate Mobile
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="number" class="form-control col-md-7 col-xs-12" name = "alt_mobile">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Email
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="email" class="form-control col-md-7 col-xs-12" name = "email">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Date of Birth
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="date" class="form-control col-md-7 col-xs-12" name = "dob">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Gender
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="radio" name="gender" value = "0"> Male
								<input type="radio" name="gender" value = "1"> Female
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Category for Work</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<select class="form-control col-md-7 col-xs-12 cat" name="cat[]" multiple="multiple">
									<option value = "-1">--select--</option>
									@forelse (App\Models\Category::get() as $cat)
									<optgroup label="{{ $cat->cat_title }}"></optgroup>
									@forelse (App\Models\SubCategory::where('scat_cat_id', $cat->cat_id)->get() as $c)										
									<option value = "{{ $c->scat_id }}">{{ $c->scat_title }}</option>
									@empty										
									@endforelse
									@empty
									@endforelse									
								</select>									
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Known Languages</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<select class="form-control col-md-7 col-xs-12 lang" name="lang[]" multiple="multiple">
									<option value = "-1">--select--</option>
									@forelse (App\Models\Language::get() as $l)
									<option value = "{{ $l->lan_id }}">{{ $l->lan_title }}</option>
									@empty
									@endforelse									
								</select>									
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Qualifications</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<select class="form-control col-md-7 col-xs-12 qua" name="qualifications[]" multiple="multiple">
									<option value = "-1">--select--</option>
									@forelse (App\Models\Qualification::get() as $q)
									<option value = "{{ $q->qua_id }}">{{ $q->qua_title }}</option>
									@empty
									@endforelse									
								</select>									
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Identity Proof
							</label>							
							<div class="col-md-6 col-sm-6 col-xs-12 text-center">
								<input type="text" class="form-control col-md-7 col-xs-12" name = "identity_no">
								<img src="{{ asset('images/no-image.png') }}" width="300" height="150" id = "id-cardPreview">
								<div class="clearfix"></div>
								<input type = "file" id ="id-card" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name="id_card">
								<label class="btn btn-success" for = "id-card">Choose Pan Card or Aadhar Card</label>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Address Proof
							</label>							
							<div class="col-md-6 col-sm-6 col-xs-12 text-center">
								<input type="text" class="form-control col-md-7 col-xs-12" name = "address_no">
								<img src="{{ asset('images/no-image.png') }}" width="300" height="150" id = "add-cardPreview">
								<div class="clearfix"></div>
								<input type = "file" id ="add-card" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name="add_card">
								<label class="btn btn-success" for = "add-card">Choose Electriciy Bill or Election Card</label>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">User Image
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12 text-center">
								<img src="{{ asset('images/blank-user.jpg') }}" width="100" height="150" id = "user-imgPreview">
								<div class="clearfix"></div>
								<input type = "file" id ="user-img" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name="user_img">
								<label class="btn btn-success" for = "user-img">Choose User Image</label>
							</div>
						</div>
						<div class="ln_solid">
						</div>
						<div class="form-group text-center">							
							<button type="submit" class="btn btn-success">Add
							</button>							
						</div>					
					</form>					
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@push('footer')
<script src="{{ asset('js/select2.min.js') }}"></script>
<script>
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}',
		validation:false,	
		processResponse : function (data) {
			console.log(data);
		}
	});	
	function geturl(name) {
		var link = '{{ route('admin.home') }}/'+name;
		return link;
	}
	
	multiSelect('.qua', 'qualification');
	multiSelect('.lang', 'language');
	multiSelect('.cat', 'category');
		
	imageUpload('id-card');
	imageUpload('add-card');
	imageUpload('user-img');
</script>
@endpush

laravel/resources/views/admin/dashboard.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="right_col" role="main">
</div>
@endsection

laravel/resources/views/admin/edit_employee.blade.php
@extends('admin.layouts.master')
@php
$ID = 'employee';
@endphp
@push('header')
<script>
	ID = '{{ $ID }}';
</script>
<style type="text/css">
img {
	object-fit: contain;
}

</style>
@section('title')
Create {{ ucwords($ID) }}
@endsection
<link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" />
@endpush
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Register {{ ucwords($ID) }}</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					<form id = "{{ $ID }}Form">
						<div class="w3layouts_mail_grid_right mail_grid no-padding">						
							<div class="col-md-2">
								<div class="form-group">
									<label class="control-label">Employee Image</label>
									<div class="text-center">
										<img src="{{ asset($emp->detail ? $emp->detail->ud_img_path : '') }}" width="150" height="150" id = "user-imgPreview">
										<div class="clearfix"></div>
										<input type = "file" id ="user-img" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name="user_img">
										<label class="btn btn-success" for = "user-img">Choose User Image</label>
									</div>
									<div class="clearfix"></div>
								</div>
								<div class="form-group text-center">
									<label class="control-label">Employee ID:</label>
									<label class="control-label">{{ $emp->detail ? $emp->detail->ud_emp_id : '' }}</label>
								</div>
							</div>
							<div class="col-md-5">
								<input type="hidden" name="id" value="{{ $emp->id }}">
								<input type="hidden" name="emp_id" value="{{ $emp->detail ? $emp->detail->ud_emp_id : ''}}">
								<div>
									<label class="control-label">Full Name</label>
									<input type="text" class="form-control col-md-7 col-xs-12" name = "name" data-validate = "empty|alphaSpace" value="{{ $emp->name }}">
									<div class="clearfix"></div>
								</div>
								<div>
									<label class="control-label">Mobile</label>
									<input type="number" class="form-control col-md-7 col-xs-12" name = "mobile" data-validate = "empty|mobile" value = "{{ $emp->detail ? $emp->detail->ud_mobile : ''}}">
									<div class="clearfix"></div>

								</div>
								<div>
									<label class="control-label">Alternate Mobile</label>
									<input type="number" class="form-control col-md-7 col-xs-12" name = "alt_mobile" data-validate = "empty|mobile" value = "{{ $emp->detail ? $emp->detail->ud_alt_mobile : ''}}">
									<div class="clearfix"></div>

								</div>
								<div>
									<label class="control-label">Email</label>
									<input type="email" class="form-control col-md-7 col-xs-12" name = "email" data-validate = "empty|email" value = "{{ $emp->email }}">
									<div class="clearfix"></div>

								</div>

								<div>
									<label class="control-label">Date of Birth</label>					
									<input type="date" class="form-control col-md-7 col-xs-12" name = "dob"  value = "{{ $emp->detail ? $emp->detail->ud_dob : ''}}">
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="col-md-5 ">
								<div style="margin-bottom: 22px;">
									<label class="control-label">Gender</label>
									<div class="clearfix"></div>
									<div>										
										<input type="radio" name="gender" value = "0" {{ $emp->detail ? ($emp->detail->ud_gender ? 'checked' : '') : ''}}> Male
										<input type="radio" name="gender" value = "1" {{ $emp->detail ? ($emp->detail->ud_gender ? '' : 'checked') : '' }}> Female
									</div>
									<div class="clearfix"></div>
								</div>
								<div class="form-group">
									<label class="control-label">Category for Work</label>
									<select class="form-control col-md-7 col-xs-12 cat" name="cat[]" multiple="multiple">
										<option value = "-1">--select--</option>
										@forelse (App\Models\Category::get() as $cat)
										<optgroup label="{{ $cat->cat_title }}"></optgroup>
										@forelse (App\Models\SubCategory::where('scat_cat_id', $cat->cat_id)->get() as $c)
										<option value = "{{ $c->scat_id }}" {{ in_array($c->scat_id, explode(',',$emp->detail->ud_category)) ? 'selected' : ''}}>{{ $c->scat_title }}</option>
										@empty										
										@endforelse
										@empty
										@endforelse									
									</select>									
									<div class="clearfix"></div>

								</div>
								<div class="form-group">
									<label class="control-label">Known Languages</label>

									<select class="form-control col-md-7 col-xs-12 lang" name="lang[]" multiple="multiple">
										<option value = "-1">--select--</option>
										@forelse (App\Models\Language::get() as $l)
										<option value = "{{ $l->lan_id }}" {{ in_array($l->lan_id, explode(',',$emp->detail->ud_language)) ? 'selected' : '' }}>{{ $l->lan_title }}</option>
										@empty
										@endforelse									
									</select>
									<div class="clearfix"></div>

								</div>
								<div class="form-group">
									<label class="control-label">Qualifications</label>

									<select class="form-control col-md-7 col-xs-12 qua" name="qualifications[]" multiple="multiple">
										<option value = "-1">--select--</option>
										@forelse (App\Models\Qualification::get() as $q)
										<option value = "{{ $q->qua_id }}" {{ in_array($q->qua_id, explode(',',$emp->detail->ud_qualification)) ? 'selected' : '' }}>{{ $q->qua_title }}</option>
										@empty
										@endforelse									
									</select>									
									<div class="clearfix"></div>

								</div>								
							</div>
						</div>
						<div class="col-md-12">
							<h3>Upload Documents</h3>
							<div class="form-group col-md-6">
								<label class="control-label">Identity Proof
								</label>							
								<div class="text-center">
									<input type="text" class="form-control col-md-7 col-xs-12" name = "identity_no" value = "{{ $emp->detail->ud_identity_no }}">
									<div class="clearfix"></div>
									<img class = "id-card" src="{{ asset($emp->detail->ud_identity_proof) }}" id = "id-cardPreview">
									<div class="clearfix"></div>
									<input type = "file" id ="id-card" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name="id_card">
									<label class="btn btn-success" for = "id-card">Choose Pan Card or Aadhar Card</label>
								</div>
							</div>
							<div class="form-group col-md-6">
								<label class="control-label">Address Proof
								</label>							
								<div class="text-center">
									<input type="text" class="form-control col-md-7 col-xs-12" name = "address_no" value = "{{ $emp->detail->ud_address_no }}">
									<img class = "id-card" src="{{ asset($emp->detail->ud_address_proof) }}" id = "add-cardPreview">
									<div class="clearfix"></div>
									<input type = "file" id ="add-card" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name="add_card">
									<label class="btn btn-success" for = "add-card">Choose Electriciy Bill or Election Card</label>
								</div>
							</div>	
						</div>
						<div class="clearfix"></div>
						<div class="text-center">
							<button type="submit" class="btn btn-default bton">Register</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@push('footer')
<script src="{{ asset('js/select2.min.js') }}"></script>
<script>
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.index') }}',
		type:2,
		validation:false,	
		processResponse : function (data) {
			console.log(data);
		}
	});	
	function geturl(name) {
		var link = '{{ route('admin.home') }}/'+name;
		return link;
	}
	
	multiSelect('.qua', 'qualification');
	multiSelect('.lang', 'language');
	multiSelect('.cat', 'category');

	imageUpload('id-card');
	imageUpload('add-card');
	imageUpload('user-img');
</script>
@endpush

laravel/resources/views/admin/view_employees.blade.php
@extends('admin.layouts.master')

@section('title')
Employees
@endsection
@push('header')
<!-- Datatables -->
<link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
@php
$ID = 'employee';
@endphp
<script>
  var ID = '{{ $ID }}';
</script>
@endpush

@section('content')

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Employees</h3>
      </div>      
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">            
            <table id="{{ $ID }}Table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Sr. No.</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Mobile</th>
                  <th>Categories</th>
                  <th>Joining Date</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($users as $k => $e)
                <tr id = "tr-{{ $e->enq_id }}">
                  <td>{{ ++$k }}</td>
                  <td>{{ $e->name }}</td>
                  <td>{{ $e->email }}</td>
                  <td>{{  $e->detail->ud_mobile or '-' }}</td>
                  @if (isset($e->detail->ud_category))
                  @php
                  $cats = App\Models\SubCategory::whereIn('scat_id', explode(',',$e->detail->ud_category))->get();
                  $t = [];
                  $mc = [];
                  foreach ($cats as $k => $v) {   
                    $t[] = $v->scat_title;
                  }
                  $title = implode(', ',$t);
                  @endphp
                  <td>{{ $title }}</td>
                  @else
                  <td>-</td>                    
                  @endif
                  <td>{{ Carbon\Carbon::parse($e->created_at)->toDayDateTimeString() }}</td>
                  <td>                    
                    <a href="{{ route('admin.employee.edit', ['id' => $e->id]) }}" class="btn btn-info btn-xs" ><i class="fa fa-pencil"></i> View</a> | 
                    <form action="{{ route('admin.employee.destroy', ['id' => $e->id]) }}" method="post">
                      <input type="hidden" name="_method" value="delete">
                      {{ csrf_field() }}
                      <button class="btn btn-danger btn-xs" ><i class="fa fa-trash"></i> Delete</button>
                    </form>
                  </td>
                </tr>
                @empty
                <tr>
                  <td colspan = "7" class="text-center">No {{ $ID }} Found</td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>


    <div class="modal fade" id="{{ $ID }}Modal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="{{ $ID }}ModalLabel">View {{ ucwords($ID) }}</h4>
          </div>
          <div class="modal-body">
            <form id = "{{ $ID }}Form" class="form-horizontal form-label-left">              
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Full Name:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly type="text"  class="form-control no-borders"  name="full_name">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Category:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly type="text"  class="form-control no-borders"  name="scat_title">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Company Name:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly class="form-control no-borders" type="text" name="title">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Mobile:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly class="form-control no-borders" type="number" name="mobile" id ="enq-mobile">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Email:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly class="form-control no-borders" type="email" name="email" required>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">City:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly class="form-control no-borders" type="text" name="city" id ="enq-mobile">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">From:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly class="form-control no-borders" type="date" name="from">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">To:</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <input readonly class="form-control no-borders" type="date" name="to">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Query:
                </label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <textarea readonly class="form-control no-borders" rows="3" name = "query">Query</textarea>
                </div>
              </div>
            </form>             
            <div class="clearfix"></div>          
          </div>          
        </div>
      </div>
    </div>

    <div class="modal fade" id="{{ $ID }}DModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Are You Sure?</h4>
            <br>
            <div>
              <form id = "{{ $ID }}DForm">                
                <button type = "button" class="btn btn-danger" id = "yes">Yes</button>
                <button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
              </form>
            </div>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@push('footer')
<script src="{{ asset('admin-assets/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
{{-- <script src="{{ asset('admin-assets/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script> --}}
<script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>

<script type="text/javascript">  
  var update = "{{ url('admin/'.$ID) }}",
  deleteU = "{{ url('admin/'.$ID) }}",
  store = "{{ route('admin.'.$ID.'.store') }}";

  Table.init(ID);
  function geturl(id) {
    var link = '{{ route('admin.enquiry.index') }}/'+id+'/edit';
    return link;
  }
  function view(id) {
    $.get(geturl(id), function(data) {
      $('#'+ID+'Modal').modal('toggle');
      $.each($('#'+ID+'Form')[0].elements,function(k, v) {
        var name = $(v).attr('name');        
        $(v).val(data[name]);
      });
    });
  }  

</script>
@endpush